"""empty message

Revision ID: 15855acc12cc
Revises: a75d2e3808fb
Create Date: 2024-06-13 09:05:21.042291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15855acc12cc'
down_revision = 'a75d2e3808fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
