"""empty message

Revision ID: 58e3d21352b8
Revises: 9442c4a58f70
Create Date: 2024-06-13 10:31:44.150558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e3d21352b8'
down_revision = '9442c4a58f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
